url: 'http://localhost:8082'

mongodb:
  connectionString:       "mongodb://localhost:27017/uptime"# alternative to setting server, database, user and password separately

monitor:
  name:                   origin
  apiUrl:                 'http://localhost:8082/api' # must be accessible without a proxy
  pollingInterval:        10000      # ten seconds
  timeout:                5000       # five seconds
  userAgent:              NodeUptime/3.0 (https://github.com/fzaninotto/uptime)

analyzer:
  updateInterval:         60000      # one minute
  qosAggregationInterval: 600000     # ten minutes
  pingHistory:            8035200000 # three months

autoStartMonitor: true

plugins:
  - ./plugins/console
  - ./plugins/geckoboard
  - ./plugins/pagerduty
  
geckoboard:
  api_key: < geckoboard API key >
  reporting_interval: 60 # in seconds
  update_ts_widget_urls:  # sequence of urls of text widgets to publish a 'last updated' message

pagerduty:
  serviceKey: <pagerduty-service-key>
  autoresolve: false